export const FUND_NAME_MAP = {
  FPV_BTG_PACTUAL_RECAUDADORA: 'BTG PACTUAL RECAUDADORA',
  FPV_BTG_PACTUAL_ECOPETROL: 'BTG PACTUAL ECOPETROL',
  DEUDAPRIVADA: 'DEUDA PRIVADA',
  'FDO-ACCIONES': 'FONDO ACCIONES',
  FPV_BTG_PACTUAL_DINAMICA: 'BTG PACTUAL DINAMICA',
} as const;